//! User and token operations.
//!
//! Tokens are stored only as a SHA-256 hash; the plaintext is shown once at
//! creation. An agent token is a token tied to a human plus an agent-name
//! marker, so attribution stays human-meaningful ("dylan via claude-code").
//! Token *verification* (resolving a presented token to an
//! [`Actor`](crate::actor::Actor)) lives in the server's auth middleware
//! (T-0130); this module owns issuance.

use diesel::prelude::*;
use diesel_dualdb::types::{Timestamp, Uuid};
use diesel_dualdb::DualConnection;
use sha2::{Digest, Sha256};

use super::{Result, ServiceError};
use crate::actor::Actor;
use crate::models::UserRow;
use crate::schema::{tokens, users};

/// A freshly minted token: the plaintext (shown once) and its row id.
#[derive(Debug, Clone)]
pub struct IssuedToken {
    /// The bearer token to hand to the client. Not stored in plaintext.
    pub plaintext: String,
    /// The token row id.
    pub id: uuid::Uuid,
}

/// Create a user.
pub fn create_user(
    conn: &mut DualConnection,
    username: &str,
    display_name: &str,
    email: Option<&str>,
    is_admin: bool,
) -> Result<UserRow> {
    if username.trim().is_empty() {
        return Err(ServiceError::Validation("username is empty".into()));
    }
    let id = uuid::Uuid::new_v4();
    diesel::insert_into(users::table)
        .values((
            users::id.eq(Uuid(id)),
            users::username.eq(username),
            users::display_name.eq(display_name),
            users::email.eq(email),
            users::is_admin.eq(is_admin),
            users::active.eq(true),
            users::created_at.eq(Timestamp(chrono::Utc::now())),
        ))
        .execute(conn)?;
    get_user(conn, id)
}

/// Fetch a user by id.
pub fn get_user(conn: &mut DualConnection, id: uuid::Uuid) -> Result<UserRow> {
    users::table
        .filter(users::id.eq(Uuid(id)))
        .select(UserRow::as_select())
        .first(conn)
        .optional()?
        .ok_or_else(|| ServiceError::NotFound(format!("user {id}")))
}

/// Fetch a user by username.
pub fn get_user_by_name(conn: &mut DualConnection, username: &str) -> Result<UserRow> {
    users::table
        .filter(users::username.eq(username))
        .select(UserRow::as_select())
        .first(conn)
        .optional()?
        .ok_or_else(|| ServiceError::NotFound(format!("user {username:?}")))
}

/// Hash a token's plaintext for storage / lookup.
pub fn hash_token(plaintext: &str) -> String {
    let mut h = Sha256::new();
    h.update(plaintext.as_bytes());
    let digest = h.finalize();
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// Issue a token for a user, optionally tied to a named agent. The plaintext is
/// generated by the caller (the server, which has secure randomness) and passed
/// in; only its hash is persisted.
pub fn issue_token(
    conn: &mut DualConnection,
    user_id: uuid::Uuid,
    name: &str,
    agent_name: Option<&str>,
    plaintext: &str,
) -> Result<IssuedToken> {
    // Ensure the user exists (also gives a clean NotFound rather than an FK error).
    get_user(conn, user_id)?;

    let id = uuid::Uuid::new_v4();
    diesel::insert_into(tokens::table)
        .values((
            tokens::id.eq(Uuid(id)),
            tokens::user_id.eq(Uuid(user_id)),
            tokens::name.eq(name),
            tokens::agent_name.eq(agent_name),
            tokens::token_hash.eq(hash_token(plaintext)),
            tokens::created_at.eq(Timestamp(chrono::Utc::now())),
        ))
        .execute(conn)?;

    Ok(IssuedToken {
        plaintext: plaintext.to_string(),
        id,
    })
}

/// Resolve a presented bearer token to an [`Actor`].
///
/// Returns `None` if the token is unknown, revoked, or belongs to an inactive
/// user. On success, bumps the token's `last_used_at`. Token comparison is by
/// stored SHA-256 hash; the plaintext is never persisted.
pub fn resolve_actor(conn: &mut DualConnection, plaintext: &str) -> Result<Option<Actor>> {
    let hash = hash_token(plaintext);
    let row = tokens::table
        .inner_join(users::table.on(users::id.eq(tokens::user_id)))
        .filter(tokens::token_hash.eq(&hash))
        .filter(tokens::revoked_at.is_null())
        .filter(users::active.eq(true))
        .select((tokens::user_id, tokens::agent_name))
        .first::<(Uuid, Option<String>)>(conn)
        .optional()?;

    match row {
        Some((user_id, agent)) => {
            diesel::update(tokens::table.filter(tokens::token_hash.eq(&hash)))
                .set(tokens::last_used_at.eq(Some(Timestamp(chrono::Utc::now()))))
                .execute(conn)?;
            Ok(Some(Actor {
                user: user_id.0,
                agent,
            }))
        }
        None => Ok(None),
    }
}

/// Revoke a token by id (idempotent set of `revoked_at`).
pub fn revoke_token(conn: &mut DualConnection, id: uuid::Uuid) -> Result<()> {
    diesel::update(tokens::table.filter(tokens::id.eq(Uuid(id))))
        .set(tokens::revoked_at.eq(Some(Timestamp(chrono::Utc::now()))))
        .execute(conn)?;
    Ok(())
}
